### ISSUE TITLE
Add Install and Usage sections

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/dir-index-html#11]
Not sure how to use this repo? Related to #10.

**Comment by Kubuxu** [comment]
I didn't know it existed and some time ago I would love to use this. :smile:

**Comment by lgierth** [comment]
This repo is not be used standalone, so it has neither install nor usage instructions :) It's used by the gateway code in go-ipfs. It'll be merged into the gateway package, once the gateway has been extracted from go-ipfs.

**Comment by RichardLitt** [comment]
Cool. Noted in the README.
