### ISSUE TITLE
Add CID Column

### ISSUE THREAD

**Issue by lidel** [ipfs/dir-index-html#15]
> **fiatjaf:** why doesn't the gateway http output for unixfs dirs show the hashes of linked files?

Good question!

- I suspect CIDs could be easily added to listing, next to the Size column
- CIDs could be clickable links that  open item as a new "root path"  
  - this also enables users to copy direct link to image or a subdirectory 
- It probably requires changes to  https://github.com/ipfs/dir-index-html  and then switching go-ipfs to new version

cc @olizilla  @fiatjaf

**Comment by jessicaschilling** [comment]
Closing this one in favor of the combined dir-index-html UI bounty issue here: https://github.com/ipfs/dir-index-html/issues/37
