### ISSUE TITLE
video files don't have a proper icon

### ISSUE THREAD

**Issue by swedneck** [ipfs/dir-index-html#19]
Currently video files have a generic "file" icon, they should have an icon that indicates that they are videos.

**Comment by jessicaschilling** [comment]
@swedneck -- It's been a while since this issue was opened, but might you be interested in making a PR? You can find the standard icon set here: http://127.0.0.1:8080/ipfs/QmVrEsy8JjQAugWm48XvFopi9mEKgxcTXdFmEZ6VR2q6rx/

**Comment by jessicaschilling** [comment]
Looks like we're missing icons for .mkv, .mov, and .wmv files among the most commonly encountered video file types. 

![image](https://user-images.githubusercontent.com/1507828/81016289-618c4580-8e1d-11ea-8d03-24a09c93fd65.png)
