### ISSUE TITLE
Display viewed directory's size

### ISSUE THREAD

**Issue by swedneck** [ipfs/dir-index-html#25]
The size of child directories are already shown, it would be nice to also show the size of the current directory.
Example:
![Example](https://user-images.githubusercontent.com/40505480/77464849-120f2e80-6e08-11ea-973f-e048620fcb4a.png)

**Comment by jessicaschilling** [comment]
@swedneck Great idea! Might you have time to make a PR on it?

**Comment by swedneck** [comment]
I don't even know where to begin with modifying this repo, i haven't touched go beyond compiling things.

**Comment by jessicaschilling** [comment]
@swedneck No worries, just thought I'd ask in case! 😊

**Comment by jessicaschilling** [comment]
Closing this one in favor of the combined dir-index-html UI bounty issue here: https://github.com/ipfs/dir-index-html/issues/37
