### ISSUE TITLE
5001 port conflict with Cisco Anywhere Connect VPN

### ISSUE THREAD

**Issue by fliiteAI** [ipfs/dir-index-html#33]
Out of the box install of IPFS will conflict with Cisco Anywhere Connect.  In my particular case it was running on OSX Catalina.  I had a standard install of the VPN software with not customizations.   I downloaded IPFS Desktop and spent better part of a day tracking down why the daemon wouldn't start.  On the enterprise front CISCO VPN software is pretty standard and this will get in the way of enterprise level deployments.   I think the notifications should come front and center for non-computer science types so they understand they have a port conflict.
YMMV

**Comment by Stebalien** [comment]
Ongoing discussion in https://github.com/ipfs/go-ipfs/issues/874.

**Comment by jessicaschilling** [comment]
Let's keep tracking in ipfs/go-ipfs#874 ... I'll close this here for the sake of avoiding duplication. Thanks!
