### ISSUE TITLE
Improve social media previews

### ISSUE THREAD

**Issue by lidel** [ipfs/dir-index-html#34]
People share links on social media and forums. Most of places have "oneboxing" logic, which turns link into more rich preview card with title, one line summary, and a thumbnail:

> <img width="447" alt="shared link card on facebook" src="https://user-images.githubusercontent.com/157609/85234005-d980f000-b40a-11ea-91c6-62059a7dcfbf.png">

### Problem

Right now, when someone shares IPFS dir listing on social media, the card includes title, but instead of summary, we get random text from the page and no image.

Our directory listing pages should include relevant metadata in meta headers, so if someone shares a link to a directory, it looks better, provides educational information that the link is content-addressed + perhaps has an IPFS-themed thumbnail to make share more interesting.

### TODO

I beleive we should make it look good in three most popular contexts:

- [x] Open Graph (Facebook) – https://ogp.me
- [x] Twitter Cards - https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards

### Useful links

- Sample dir listing for testing (Project Apollo Archives): https://bafybeiccfclkdtucu6y4yc5cpr6y3yuinr67svmii46v5cfcrkp47ihehy.ipfs.dweb.link/ 
- prior art: meta headers at blog.ipfs.io: https://github.com/ipfs/blog/blob/83263930019e794b4fcf809ef19599551d44d43c/layouts/partials/head.html#L25-L42
- Facebook
  - sharing debugger: https://developers.facebook.com/tools/debug/ (sadl yrequires account, which I don't have :( )
  - meta tags docs https://developers.facebook.com/docs/sharing/webmasters/
- http://debug.iframely.com - debug URLs against oEmbed, Twitter Cards, Open Graph and Iframely specs

cc @jessicaschilling (this is the thing I briefly mentioned it the other day)

**Comment by jessicaschilling** [comment]
I think my Facebook developer account is still active. I'll play around with this.

**Comment by jessicaschilling** [comment]
For my own reference - here are the ones we implemented in docs: https://github.com/ipfs-inactive/docs/issues/343#issuecomment-562371984

**Comment by jessicaschilling** [comment]
This can be closed via https://github.com/ipfs/dir-index-html/pull/36
