### ISSUE TITLE
HTTP Error 404 for /favicon.ico 

### ISSUE THREAD

**Issue by lidel** [ipfs/dir-index-html#35]
Directory listings are missing favicon definition, which makes browser to make request for implicit `/favicon.ico` which always fails.

To illustrate, opening https://bafybeiccfclkdtucu6y4yc5cpr6y3yuinr67svmii46v5cfcrkp47ihehy.ipfs.dweb.link/ produces two requests:

> ![2020-06-21--22-11-52](https://user-images.githubusercontent.com/157609/85234237-434dc980-b40c-11ea-9e67-fd8010f22398.png)

We could either add a favicon (would have to be inlined as dataurl to work in every context) or supress the request with:

```html
<link rel="shortcut icon"type="image/x-icon" href="data:image/x-icon;,">
```

**Comment by jessicaschilling** [comment]
https://github.com/ipfs/dir-index-html/pull/36 should close this. Out for review.
