### ISSUE TITLE
Not getting latest sites with cloudflare ipfs

### ISSUE THREAD

**Issue by kcubeterm** [ipfs/dir-index-html#49]
My latest sites show on ipfs with ipns but not with cloudflare getway.

Latest is https://ipfs.io/ipns/k51qzi5uqu5diddda9nm0f91pd9o2iaag71td786zosczje4kll4u9wmrwzbjf

Here cloudflare showing old sites. 
https://cloudflare-ipfs.com/ipns/k51qzi5uqu5diddda9nm0f91pd9o2iaag71td786zosczje4kll4u9wmrwzbjf

**Comment by jessicaschilling** [comment]
This sounds like an issue with Cloudflare's gateway, not a bug in the directory index page code. Closing but feel free to open if this is not the case.

**Comment by kcubeterm** [comment]
Now it's working. It took time. Thanks
