### ISSUE TITLE
Humanize file sizes

### ISSUE THREAD

**Issue by jbenet** [ipfs/dir-index-html#7]
the sizes are annoying to read, would be nicer as humanized (with the full bytes in the html, but not shown, or if shown, shown as well)

**Comment by jessicaschilling** [comment]
See screenshot in https://github.com/ipfs/dir-index-html/issues/2.

**Comment by ribasushi** [comment]
@jessicaschilling what screenshot are you referring to...?

**Comment by jessicaschilling** [comment]
@ribasushi Weird, it's in the original comment in that issue but is displaying intermittently. Direct link: https://gateway.ipfs.io/ipfs/QmSNtHnRxSnmJCZuHPgXT9ivBSB9dTjgFKg4B18xsYKtUN/cap.png

**Comment by jessicaschilling** [comment]
Closing; this one's been fixed somewhere along the way. 
![image.png](https://images.zenhubusercontent.com/5ce5bf88b1698b1ceb4ce811/59fab925-7ddc-42e6-9850-2d64dec7416f)
