### ISSUE TITLE
Directories with "extensions" use dedicated icons

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/dir-index-html#8]
It is quite misleading.
![](https://ipfs.io/ipfs/QmaN4qnQDVkvJXVRRMEwwxR3LK4hxN5nbzWLn9utAdag6G/screencap.2016-02-22T14:33:13Z.png)

**Comment by jessicaschilling** [comment]
@Kubuxu This is an old issue, but if you get a moment, can you please illustrate/screenshot? Thanks.

**Comment by jessicaschilling** [comment]
Related: ipfs/go-ipfs#8810

**Comment by jessicaschilling** [comment]
Closing in favor of ipfs/go-ipfs#8810, as it's a precursor to being able to do this work.
